### ISSUE TITLE
Problema de layout

### ISSUE THREAD

**Issue by i53nn4** [andrecrispim/UNISUAM#4]
Tela do S5 - 1920x1080 está com problema no layout, imagens abaixo:

![s5 - erro_menu](https://cloud.githubusercontent.com/assets/8302354/10770022/4348ac66-7cd0-11e5-89e1-7ba61aea434c.png)
![s5 - erro_logo](https://cloud.githubusercontent.com/assets/8302354/10770023/43665298-7cd0-11e5-82e9-04fd463028dd.png)

A imagem abaixo é do winphone, mas em telas com resolução pequena o no boletim o nome da disciplina fica sobre a nota.

![nokia lumen 520 -boletim](https://cloud.githubusercontent.com/assets/8302354/10770146/e1cb547e-7cd0-11e5-8aa5-cebf68bdc5db.png)

**Comment by andrecrispim** [comment]
O boletim tá assim desde o inicio, inclusive nas outras plataformas, mas posso dar uma olhada.

**Comment by andrecrispim** [comment]
Os dois problemas foram corrigidos na versão 2.0.3
